version: '3'

services:
  judge0:
    image: judge0/judge0-ce:1.13.0
    ports:
      - "2358:2358"
    volumes:
      - ./judge0-data:/judge0-data
    privileged: true
    environment:
      - VIRTUAL_HOST=judge0
      - VIRTUAL_PORT=2358
      - RAILS_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=judge0
      - POSTGRES_USER=judge0
      - POSTGRES_PASSWORD=judge0
      - SECRET_KEY_BASE=supersecretkey
    depends_on:
      - db
      - redis

  db:
    image: postgres:13.0
    environment:
      - POSTGRES_DB=judge0
      - POSTGRES_USER=judge0
      - POSTGRES_PASSWORD=judge0
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  redis:
    image: redis:6.0
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  postgres-data:
  redis-data:
  judge0-data: 